name: Release with Goreleaser
on:
  push:
    branches:
      - avichalp/goreleaser
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goreleaser/goreleaser-cross:v1.18

    steps:
      - uses: actions/checkout@v3
        with:          
          submodules: 'true'
      - run: git fetch --prune --unshallow
      - uses: actions/setup-go@v3
        with:
          go-version: v1.19.x            
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          # skip git checks for testing
          # --snapshot is used for testing; it doesn't publish artifacts
          args: release --clean --skip-validate --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}